apiVersion: batch/v1
kind: CronJob
metadata:
  name: backuptominio
  namespace: db
spec:
  schedule: "00 23 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: 192.168.154.128:5000/custome-backup:0.0.0

            env:
            - name: DBNAME
              value: "gitea"
            - name: DBUSER
              value: root
            - name: DBPASSWORD
              value: "gitea"
            - name: DBHOST
              value: 10.42.2.13 
            command: ["/bin/bash"]

            args: ["-c", " /usr/local/bin/mc alias set myminio http://192.168.154.128:9000 minioadmin minioadmin && ./script.sh"]
            readinessProbe:
              exec:
                command: ["/bin/sh", "-c", "echo ready"]
              initialDelaySeconds: 5
              periodSeconds: 10
            livenessProbe:
              exec:
                command: ["/bin/sh", "-c", "echo live"]
              initialDelaySeconds: 5
              periodSeconds: 10
