apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: k3s-cluster
  namespace: metallb-system
spec:
  addresses:
  - 192.168.154.200-192.168.154.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
   - k3s-cluster
