apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-address
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.200-192.168.1.240
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
   - pool-address
