[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
DNS.2 = mashine1
DNS.3 = mashine2
DNS.4 = mashine3
DNS.5 = mashine4
DNS.6 = mashine5
DNS.7 = mashie1.noob.net
DNS.8 = mashine2.noob.net
DNS.9 = mashine3.noob.net
DNS.10 = mashine4.noob.net
DNS.11 = mashine5.noob.net

IP.1 = 127.0.0.1
IP.2 = 192.168.1.116
IP.3 = 192.168.1.117
IP.4 = 192.168.1.118
IP.5 = 192.168.1.119
IP.6 = 192.168.1.121
