[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_req]
basicConstraints = critical, CA:FALSE
keyUsage = critical, nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names
[alt_names]
DNS.1 = localhost
DNS.2 = kubernetes
DNS.3 = kubernetes.default
DNS.4 = kubernetes.defalut.svc
DNS.5 = kubernetes.defalut.svc.cluster # (name cluster)
DNS.6 = kubernetes.default.svc.cluster.local # (name cluster )
DNS.7 = mashie6.noob.net
DNS.8 = mashine7.noob.net
DNS.9 = mashine8.noob.net
DNS.10 = mashine6
DNS.11 = mashine7
DNS.12 = mashine8
IP.1 = 127.0.0.1
IP.2 = 10.10.0.1 # cidr-cluster
IP.3 = 192.168.1.102
IP.4 = 192.168.1.108
IP.5 = 192.168.1.106
IP.6 = 192.168.1.245 # Load-Balancer
