apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
