apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: docker
          image: 192.168.154.128:5000/gitlab
          ports: 
          - name: ssh-port
            containerPort: 22
          - name: web
            containerPort: 80
          - name: https
            containerPort: 443
          env:
          - name: GITLAB_OMNIBUS_CONFIG
            value: external_url 'http://192.168.154.174'
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - name: web
    port: 80
    targetPort: web
    nodePort: 30800
