apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-data
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
