apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pvc
  namespace: db
  labels:
    storage.k8s.io/name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
